//@baseUrl = http://localhost:5000
@baseUrl = http://191.237.200.219:5000

###

GET {{baseUrl}}/shoppingCart/123

###

POST {{baseUrl}}/shoppingCart/123/items
Content-Type: application/json

[1, 2]

###

GET {{baseUrl}}/events?start=4